# Generated by Django 5.2.17 on 2026-09-23 18:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('HOSPITAL', 'Hospital'), ('CENTRO_SALUD', 'Centro de salud'), ('BODEGA', 'Bodega'), ('AREA_SALUD', 'Área de salud'), ('FARMACIA_INSTITUCIONAL', 'Farmacia institucional')], max_length=25)),
                ('departamento', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.CharField(max_length=100, unique=True)),
                ('fecha_fabricacion', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('cantidad_inicial', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('principio_activo', models.CharField(max_length=200)),
                ('presentacion', models.CharField(max_length=150)),
                ('fabricante', models.CharField(max_length=200)),
                ('registro_sanitario', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('BLOQUEO', 'Bloqueo'), ('RETIRO', 'Retiro'), ('SOSPECHA', 'Sospecha')], max_length=10)),
                ('motivo', models.CharField(max_length=1000)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alertas', to='core.lote')),
            ],
            options={
                'ordering': ['fecha', 'id'],
            },
        ),
        migrations.AddField(
            model_name='lote',
            name='medicamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='core.medicamento'),
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('tipo_movimiento', models.CharField(choices=[('INGRESO', 'Ingreso'), ('TRASLADO', 'Traslado')], max_length=10)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='core.establecimiento')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='core.lote')),
                ('origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salidas', to='core.establecimiento')),
            ],
            options={
                'ordering': ['fecha_movimiento', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='lote',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad_inicial__gt', 0)), name='lote_cantidad_positiva'),
        ),
        migrations.AddConstraint(
            model_name='lote',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_vencimiento__gt', models.F('fecha_fabricacion'))), name='lote_fechas_validas'),
        ),
        migrations.AddConstraint(
            model_name='movimiento',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='movimiento_cantidad_positiva'),
        ),
        migrations.AddConstraint(
            model_name='movimiento',
            constraint=models.CheckConstraint(condition=models.Q(('tipo_movimiento', 'INGRESO'), models.Q(('origen__isnull', False), ('tipo_movimiento', 'TRASLADO'), models.Q(('origen', models.F('destino')), _negated=True)), _connector='OR'), name='movimiento_ruta_valida'),
        ),
    ]
